requirements:
  sensors:
    - Os:
        dont_send: True
        
discovery:
  homeassistant: # Must match discovery preset name
    - topic: "monitor_state/set"
      type: "switch"
      payload:
        name: "Monitor"
        icon: "mdi:monitor-star"